vich_uploader:
    db_driver: orm

    mappings:
       ingredient:
           uri_prefix: /images/ingredient
           upload_destination: '%kernel.project_dir%/public/images/ingredient'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       recipe:
           uri_prefix: /images/recipe
           upload_destination: '%kernel.project_dir%/public/images/recipe'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer