vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       ingredients:
           uri_prefix: /images/ingredients
           upload_destination: '%kernel.project_dir%/public/images/ingredients'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       recipes:
           uri_prefix: /images/recipes
           upload_destination: '%kernel.project_dir%/public/images/recipes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
