vich_uploader:
    db_driver: orm

    mappings:
       ingredients:
           uri_prefix: /upload/ingredients
           upload_destination: '%kernel.project_dir%/public/upload/ingredients'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
