vich_uploader:
    db_driver: orm

    mappings:
       ingredients:
           uri_prefix: /images/ingredients
           upload_destination: '%kernel.project_dir%/public/images/ingredients'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       recettes:
           uri_prefix: /images/recettes
           upload_destination: '%kernel.project_dir%/public/images/recettes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

