vich_uploader:
    db_driver: orm

    mappings:
       ingredient:
           uri_prefix: /images/ingredient
           upload_destination: '%kernel.project_dir%/public/images/ingredient'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            # inject_on_load: false
            # delete_on_update: true
            # delete_on_remove: true
